LIVECONNECT = 'netscape.javascript:plugin:jar:1.6'
JNLP = 'javax.jnlp:jnlp:jar:1.2'

repositories.remote << 'http://www.ibiblio.org/maven2/'
repositories.remote << 'http://druid.systemsbiology.net/~wwu/maven2-repo'

define 'gaggle' do
  project.version = '2.0.0'
  project.group = 'org.systemsbiology.gaggle'

  define 'gaggle-core' do
    package :jar
  end

  define 'gaggle-connector' do
    compile.with JNLP
    compile.with project('gaggle-core')
    package :jar
  end

  define 'gaggle-bridge' do
    compile.with LIVECONNECT
    compile.with project('gaggle-core')
    package :jar
  end
end

